from hopwise.model.general_recommender.admmslim import ADMMSLIM
from hopwise.model.general_recommender.bpr import BPR
from hopwise.model.general_recommender.cdae import CDAE
from hopwise.model.general_recommender.convncf import ConvNCF
from hopwise.model.general_recommender.dgcf import DGCF
from hopwise.model.general_recommender.diffrec import DiffRec
from hopwise.model.general_recommender.dmf import DMF
from hopwise.model.general_recommender.ease import EASE
from hopwise.model.general_recommender.enmf import ENMF
from hopwise.model.general_recommender.fism import FISM
from hopwise.model.general_recommender.gcmc import GCMC
from hopwise.model.general_recommender.itemknn import ItemKNN
from hopwise.model.general_recommender.ldiffrec import LDiffRec
from hopwise.model.general_recommender.lightgcn import LightGCN
from hopwise.model.general_recommender.line import LINE
from hopwise.model.general_recommender.macridvae import MacridVAE
from hopwise.model.general_recommender.multidae import MultiDAE
from hopwise.model.general_recommender.multivae import MultiVAE
from hopwise.model.general_recommender.nais import NAIS
from hopwise.model.general_recommender.nceplrec import NCEPLRec
from hopwise.model.general_recommender.ncl import NCL
from hopwise.model.general_recommender.neumf import NeuMF
from hopwise.model.general_recommender.ngcf import NGCF
from hopwise.model.general_recommender.nncf import NNCF
from hopwise.model.general_recommender.pop import Pop
from hopwise.model.general_recommender.ract import RaCT
from hopwise.model.general_recommender.random import Random
from hopwise.model.general_recommender.recvae import RecVAE
from hopwise.model.general_recommender.sgl import SGL
from hopwise.model.general_recommender.simplex import SimpleX
from hopwise.model.general_recommender.slimelastic import SLIMElastic
from hopwise.model.general_recommender.spectralcf import SpectralCF
