# @Time   : 2025
# @Author : Giacomo Medda, Alessandro Soccol
# @Email  : giacomo.medda@unica.it, alessandro.soccol@unica.it

"""Unit tests for utilities under ``hopwise.model``.

Each module under ``hopwise.model`` is covered by its own ``unittest.TestCase`` subclass so that
new tests for other utilities (losses, layers, ...) can be added here as additional classes.
Currently only the constrained-decoding logits processors are tested.
"""

import os
import sys
import unittest

sys.path.append(os.getcwd())

import torch
from tokenizers import Tokenizer, pre_tokenizers
from tokenizers import models as token_models
from tokenizers import processors as token_processors
from tokenizers import trainers as token_trainers
from transformers import PreTrainedTokenizerFast

from hopwise.model.logits_processor import (
    ConstrainedLogitsProcessorWordLevel,
    PLMLogitsProcessorWordLevel,
)
from hopwise.utils import KnowledgeEvaluationType


def build_word_level_tokenizer(vocab, special_tokens):
    """Build a minimal word-level tokenizer mirroring ``KnowledgePathDataset._init_tokenizer``.

    This avoids building a full dataset while producing a tokenizer with the same vocabulary
    layout (special tokens + U/I/E/R word-level tokens) and the ``[BOS] ... [EOS]`` template
    the logits processors rely on.
    """
    tokenizer_object = Tokenizer(token_models.WordLevel(unk_token="[UNK]"))
    tokenizer_object.pre_tokenizer = pre_tokenizers.Split(" ", "removed")

    trainer = token_trainers.WordLevelTrainer(
        vocab_size=len(vocab) + len(special_tokens), special_tokens=special_tokens
    )
    tokenizer_object.train_from_iterator(vocab, trainer=trainer)

    tokenizer_object.post_processor = token_processors.TemplateProcessing(
        single="[BOS] $A [EOS]",
        special_tokens=[(token, tokenizer_object.token_to_id(token)) for token in ["[BOS]", "[EOS]"]],
    )

    return PreTrainedTokenizerFast(
        tokenizer_object=tokenizer_object,
        eos_token="[EOS]",
        bos_token="[BOS]",
        pad_token="[PAD]",
        unk_token="[UNK]",
        mask_token="[MASK]",
    )


class TestLogitsProcessors(unittest.TestCase):
    """Tests for the constrained-decoding logits processors in ``hopwise.model.logits_processor``.

    A tiny collaborative knowledge graph is used to keep the expected candidate sets easy to
    reason about:

    - users ``U0``, ``U1``; items ``I0``, ``I1``, ``I2``; entity ``E5`` (``E6`` is a valid token
      that is intentionally absent from the graph);
    - relation ``R0`` links users and items, relation ``R1`` links items and the entity;
    - ``U0`` interacted with ``I0``, ``I1``; ``U1`` interacted with ``I2``.

    Paths generated by these models alternate entities and relations, e.g. ``[BOS] U R I R E R I``.
    """

    SPECIAL_TOKENS = ["[BOS]", "[EOS]", "[PAD]", "[UNK]", "[MASK]"]
    VOCAB = ["U0", "U1", "I0", "I1", "I2", "E5", "E6", "R0", "R1"]

    @classmethod
    def setUpClass(cls):
        cls.tokenizer = build_word_level_tokenizer(cls.VOCAB, cls.SPECIAL_TOKENS)

    def setUp(self):
        self.tokenizer = type(self).tokenizer

        def token_id(token):
            return self.tokenizer.convert_tokens_to_ids(token)

        # Expose token ids as attributes for readable assertions (self.U0, self.R0, ...).
        for token in self.VOCAB:
            setattr(self, token, token_id(token))
        self.BOS = token_id("[BOS]")
        self.PAD = self.tokenizer.pad_token_id

        # Bidirectional collaborative knowledge graph: head -> {relation -> {tails}}.
        self.tokenized_ckg = {
            self.U0: {self.R0: {self.I0, self.I1}},
            self.U1: {self.R0: {self.I2}},
            self.I0: {self.R0: {self.U0}, self.R1: {self.E5}},
            self.I1: {self.R0: {self.U0}, self.R1: {self.E5}},
            self.I2: {self.R0: {self.U1}, self.R1: {self.E5}},
            self.E5: {self.R1: {self.I0, self.I1, self.I2}},
        }
        # User -> set of interacted (used) item tokens.
        self.tokenized_used_ids = {
            self.U0: {self.I0, self.I1},
            self.U1: {self.I2},
        }

    def make_processor(self, cls, max_sequence_length, task=KnowledgeEvaluationType.REC):
        return cls(
            tokenized_ckg=self.tokenized_ckg,
            tokenized_used_ids=self.tokenized_used_ids,
            max_sequence_length=max_sequence_length,
            tokenizer=self.tokenizer,
            task=task,
        )

    def allowed_tokens(self, scores, row=0):
        """Return the set of token ids that were not masked (i.e. score is not ``-inf``)."""
        return set(torch.nonzero(~torch.isinf(scores[row])).flatten().tolist())

    # --- ConstrainedLogitsProcessorWordLevel ---------------------------------------------------

    def test_constrained_allows_only_valid_relations(self):
        """When the next token is a relation, only relations reachable from the last entity survive."""
        processor = self.make_processor(ConstrainedLogitsProcessorWordLevel, max_sequence_length=20)
        # [BOS] U0 -> next token is a relation; U0 only participates in R0.
        input_ids = torch.LongTensor([[self.BOS, self.U0]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out), {self.R0})

    def test_constrained_allows_only_valid_tail_entities(self):
        """When the next token is an entity, only tails reachable via (head, relation) survive."""
        processor = self.make_processor(ConstrainedLogitsProcessorWordLevel, max_sequence_length=20)
        # [BOS] U0 R0 -> next token is an entity; U0 --R0--> {I0, I1}.
        input_ids = torch.LongTensor([[self.BOS, self.U0, self.R0]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out), {self.I0, self.I1})

    def test_constrained_final_step_excludes_used_items(self):
        """At the last hop, candidates are recommendable items minus the user's interacted items."""
        # max_sequence_length is chosen so that current_len == max_sequence_length - 1 - has_bos.
        processor = self.make_processor(ConstrainedLogitsProcessorWordLevel, max_sequence_length=7)
        # [BOS] U0 R0 E5 R1 -> last hop from E5 via R1 reaches {I0, I1, I2}; U0 already used {I0, I1}.
        input_ids = torch.LongTensor([[self.BOS, self.U0, self.R0, self.E5, self.R1]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out), {self.I2})

    def test_constrained_empty_candidates_fall_back_to_pad(self):
        """If every candidate is filtered out, the pad token is left unmasked to keep decoding valid."""
        processor = self.make_processor(ConstrainedLogitsProcessorWordLevel, max_sequence_length=7)
        # U0 has interacted with every reachable item, so no recommendable candidate remains.
        processor.tokenized_used_ids = {self.U0: {self.I0, self.I1, self.I2}, self.U1: {self.I2}}
        input_ids = torch.LongTensor([[self.BOS, self.U0, self.R0, self.E5, self.R1]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out), {self.PAD})

    def test_constrained_unknown_head_raises(self):
        """A head token missing from the knowledge graph is an error, not a silently empty set."""
        processor = self.make_processor(ConstrainedLogitsProcessorWordLevel, max_sequence_length=20)
        # E6 is a valid token but has no entry in tokenized_ckg.
        input_ids = torch.LongTensor([[self.BOS, self.E6]])
        scores = torch.zeros((1, len(self.tokenizer)))

        with self.assertRaises(ValueError):
            processor(input_ids, scores)

    def test_constrained_batch_rows_masked_independently(self):
        """Different sequences in a batch get their own candidate masks."""
        processor = self.make_processor(ConstrainedLogitsProcessorWordLevel, max_sequence_length=20)
        # Row 0: next relation from U0 -> {R0}. Row 1: next entity from U1 via R0 -> {I2}.
        input_ids = torch.LongTensor([[self.BOS, self.U0, self.U0], [self.BOS, self.U1, self.R0]])
        scores = torch.zeros((2, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out, row=0), {self.R0})
        self.assertEqual(self.allowed_tokens(out, row=1), {self.I2})

    # --- PLMLogitsProcessorWordLevel -----------------------------------------------------------

    def test_plm_allows_all_relations(self):
        """PLM constrains by token *type*: when a relation is expected, any relation token is allowed."""
        processor = self.make_processor(PLMLogitsProcessorWordLevel, max_sequence_length=20)
        input_ids = torch.LongTensor([[self.BOS, self.U0]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out), {self.R0, self.R1})

    def test_plm_allows_all_entities(self):
        """When an entity is expected, any node token (user/item/entity) is allowed, regardless of edges."""
        processor = self.make_processor(PLMLogitsProcessorWordLevel, max_sequence_length=20)
        input_ids = torch.LongTensor([[self.BOS, self.U0, self.R0]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        self.assertEqual(self.allowed_tokens(out), {self.U0, self.U1, self.I0, self.I1, self.I2, self.E5})

    def test_plm_final_step_excludes_used_items(self):
        """At the last hop, PLM masks the user's already interacted items."""
        processor = self.make_processor(PLMLogitsProcessorWordLevel, max_sequence_length=7)
        input_ids = torch.LongTensor([[self.BOS, self.U0, self.R0, self.E5, self.R1]])
        scores = torch.zeros((1, len(self.tokenizer)))

        out = processor(input_ids, scores)

        allowed = self.allowed_tokens(out)
        self.assertNotIn(self.I0, allowed)
        self.assertNotIn(self.I1, allowed)
        self.assertIn(self.I2, allowed)


if __name__ == "__main__":
    unittest.main()
