name: Check UV Sync and Run on CUDA 12.4

on: [
  # push,
  pull_request,
  workflow_dispatch
]

jobs:
  check-uv-sync:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
        experimental: [false]
        include:
          - python-version: "3.12"
            os: ubuntu-latest
            experimental: true

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --extra cu124 --extra all-models --extra hyper --group lint --group test --no-dev

      - name: Run Hopwise
        run: |
          # General working example
          uv run run_hopwise.py --epochs=2
          # Working check for scipy update
          uv run run_hopwise.py --model=LightGCN --epochs=2
          # Working check for DGL
          uv run run_hopwise.py --model=KGAT --epochs=2